# Sets up the Travis CI
---
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7-dev"  # 3.7 development branch; not yet working with PyYAML

# install ruby and ruby gem into environment
before_install:
  # default ruby version
  - rvm default
  # pdf-extract: https://github.com/Crossref/pdfextract
  - gem install pdf-extract

# command to install dependencies
install:
  # Install the package
  - pip install .[test_deps]
  # Install coveralls to supply test coverage to coveralls.io
  - pip install python-coveralls

# command to run tests
script:
  # Run the test suite
  - python -m pytest -v tests/ --cov=citationweb --cov-report=term-missing
  # Test the CLI
  # TODO

after_success:
  # Run coveralls to submit test coverage
  - coveralls
